apiVersion: v1
kind: ConfigMap
metadata:
  name: todo-config
  namespace: todo-app
data:
  # MongoDB connection string
  # 'mongo-service' is the Kubernetes Service name we create below
  # Kubernetes DNS resolves 'mongo-service' to MongoDB pod's IP automatically
  # Format: mongodb://username:password@hostname:port/dbname?authSource=admin
  MONGO_URI: "mongodb://admin:password123@mongo-service:27017/tododb?authSource=admin"
  
  # Port our backend Node.js app listens on
  PORT: "5000"