apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc 
  namespace: todo-app
spec:
  accessModes:
    - ReadWriteOnce
      # ReadWriteOnce = only ONE node can mount this at a time
      # Correct for a single MongoDB instance
  resources:
    requests:
      storage: 1Gi
      # Requesting 1GB of storage for MongoDB data

